#!MANAGED-CONFIG https://raw.githubusercontent.com/yasi-python/PSG/main/subscriptions/surfboard/ss_domain interval=3600 strict=false

[General]
loglevel = notify
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local
ipv6 = true
dns-server = system, 223.5.5.5
enhanced-mode-by-rule = true

[Proxy]
DIRECT = direct
❔ XX | 🔒 SS | @ai_duet [7] = ss, Peweza3.digipedia.shop, 443, encrypt-method = chacha20-ietf-poly1305, password = mps3FwmDjLrWaOVg
🇺🇸 US | 🔒 SS | @freeconfigsplus [11] = ss, us.vmagnum.win, 57456, encrypt-method = chacha20-ietf-poly1305, password = 360e21d21977dc11
🇺🇸 US | 🔒 SS | @freeconfigsplus [13] = ss, hackney-latest-strike.freesocks.work, 443, encrypt-method = chacha20-ietf-poly1305, password = XUMTygEM1jVYIvysXKqA5T
🇺🇸 US | 🔒 SS | @freevirgoolnet [1] = ss, series-a2-mec.varzesh360.co, 443, encrypt-method = chacha20-ietf-poly1305, password = u17T3BvpYaaiuW2c
🇸🇪 SE | 🔒 SS | @ip_cf_config [1] = ss, azure-sto.edgeservers.org, 48172, encrypt-method = chacha20-ietf-poly1305, password = 51yloQC8D9w1Wae7FHtI65
🇮🇷 IR | 🔒 SS | @jeyksatan [7] = ss, 37050813702269272654038283817908.international-ixp.com, 11312, encrypt-method = aes-256-gcm, password = 37fe3228-53ab-9453-19d9-e779456ef09a
🇺🇸 US | 🔒 SS | @jeyksatan [8] = ss, series-a2.varzesh360.co, 443, encrypt-method = chacha20-ietf-poly1305, password = mps3FwmDjLrWaOVg
🇺🇸 US | 🔒 SS | @megavpn_link [5] = ss, api.namasha.co, 443, encrypt-method = chacha20-ietf-poly1305, password = u17T3BvpYaaiuW2c
❔ XX | 🔒 SS | @mt_proxy [5] = ss, www2.broadalx.cfd, 40934, encrypt-method = chacha20-ietf-poly1305, password = jxfYgVB87GkSQR4U7Ce6rNBkP5URFYJfH1bFNo84pr5fWXMYCkcPAUYBCrAz7NBkpixeHgdzYYYW7jVyo9LpwSakvQ7nuKj1
🇺🇸 US | 🔒 SS | @nationalproxytelegram [2] = ss, series-a2.samanehha.co, 443, encrypt-method = chacha20-ietf-poly1305, password = mps3FwmDjLrWaOVg
🇺🇸 US | 🔒 SS | @nepo_v2ray [14] = ss, series-a2-me.samanehha.co, 443, encrypt-method = chacha20-ietf-poly1305, password = Bog0ELmMM9DSxDdQ
🇺🇸 US | 🔒 SS | @nepo_v2ray [19] = ss, series-a2-mec.samanehha.co, 443, encrypt-method = chacha20-ietf-poly1305, password = u17T3BvpYaaiuW2c
🇬🇮 GI | 🔒 SS | @outline_ir [8] = ss, imap.roomyinmita.name, 40565, encrypt-method = chacha20-ietf-poly1305, password = PXWJkSFnnX1SFSWW2B9GTYRTW5JQu2uzXCJcEjEUEV1sNn1y3m5qAREkhitCMBLnCZXDcHHpfqD3EGS4FhNht63snb55LQTv
❔ XX | 🔒 SS | @proxy_confiingir [2] = ss, ak1857.www.outline.network.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, 443, encrypt-method = chacha20-ietf-poly1305, password = u17T3BvpYaaiuW2c
❔ XX | 🔒 SS | @public504 [8] = ss, seoul.dodohee.info, 20976, encrypt-method = chacha20-ietf-poly1305, password = Gy1ddTFQcNrkyJMaoDl1da
❔ XX | 🔒 SS | @public504 [9] = ss, india.dodohee.info, 6980, encrypt-method = chacha20-ietf-poly1305, password = 4e9ufa1a2jeANAVebF0wqN
❔ XX | 🔒 SS | @red2ray [1] = ss, www.outline.network.ak1909.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, 443, encrypt-method = chacha20-ietf-poly1305, password = mps3FwmDjLrWaOVg
🇺🇸 US | 🔒 SS | @torang_vpn [4] = ss, series-a1.samanehha.co, 443, encrypt-method = chacha20-ietf-poly1305, password = W74XFALLLuw6m5IA
🇺🇸 US | 🔒 SS | @v2rayngalpha [2] = ss, series-a2-me.varzesh360.co, 443, encrypt-method = chacha20-ietf-poly1305, password = Bog0ELmMM9DSxDdQ
🇳🇱 NL | 🔒 SS | @v2rayngrit [7] = ss, switcher-nick-croquet.freesocks.work, 443, encrypt-method = chacha20-ietf-poly1305, password = 9tqhMdIrTkgQ46PvhyAtMH
🇺🇸 US | 🔒 SS | @vpn451 [3] = ss, fox-usa.outlinekeys.net, 34868, encrypt-method = chacha20-ietf-poly1305, password = 6HxRsF0fXlODpq8QbJWsS9
🇳🇱 NL | 🔒 SS | @vpn451 [6] = ss, macintosh.outlinekeys.net, 19609, encrypt-method = chacha20-ietf-poly1305, password = Q3xneMr0BQnEjHp0pkKsOf
🇳🇱 NL | 🔒 SS | @vpn451 [8] = ss, macintosh.outlinekeys.net, 19609, encrypt-method = chacha20-ietf-poly1305, password = gCTRbW1mZx8Bijc2oxHHfD
🇯🇵 JP | 🔒 SS | @vpn451 [9] = ss, sakura.outlinekeys.net, 1235, encrypt-method = chacha20-ietf-poly1305, password = GPkAia5oCnalXsWx2eF2kJ
🇺🇸 US | 🔒 SS | @vpn451 [10] = ss, fox-usa.outlinekeys.net, 34868, encrypt-method = chacha20-ietf-poly1305, password = sjKExBq5S1xENJWQGPvfGG

[Proxy Group]
PSG-MANUAL = select, PSG-AUTO, PSG-FALLBACK, ❔ XX | 🔒 SS | @ai_duet [7], 🇺🇸 US | 🔒 SS | @freeconfigsplus [11], 🇺🇸 US | 🔒 SS | @freeconfigsplus [13], 🇺🇸 US | 🔒 SS | @freevirgoolnet [1], 🇸🇪 SE | 🔒 SS | @ip_cf_config [1], 🇮🇷 IR | 🔒 SS | @jeyksatan [7], 🇺🇸 US | 🔒 SS | @jeyksatan [8], 🇺🇸 US | 🔒 SS | @megavpn_link [5], ❔ XX | 🔒 SS | @mt_proxy [5], 🇺🇸 US | 🔒 SS | @nationalproxytelegram [2], 🇺🇸 US | 🔒 SS | @nepo_v2ray [14], 🇺🇸 US | 🔒 SS | @nepo_v2ray [19], 🇬🇮 GI | 🔒 SS | @outline_ir [8], ❔ XX | 🔒 SS | @proxy_confiingir [2], ❔ XX | 🔒 SS | @public504 [8], ❔ XX | 🔒 SS | @public504 [9], ❔ XX | 🔒 SS | @red2ray [1], 🇺🇸 US | 🔒 SS | @torang_vpn [4], 🇺🇸 US | 🔒 SS | @v2rayngalpha [2], 🇳🇱 NL | 🔒 SS | @v2rayngrit [7], 🇺🇸 US | 🔒 SS | @vpn451 [3], 🇳🇱 NL | 🔒 SS | @vpn451 [6], 🇳🇱 NL | 🔒 SS | @vpn451 [8], 🇯🇵 JP | 🔒 SS | @vpn451 [9], 🇺🇸 US | 🔒 SS | @vpn451 [10]
PSG-AUTO = url-test, ❔ XX | 🔒 SS | @ai_duet [7], 🇺🇸 US | 🔒 SS | @freeconfigsplus [11], 🇺🇸 US | 🔒 SS | @freeconfigsplus [13], 🇺🇸 US | 🔒 SS | @freevirgoolnet [1], 🇸🇪 SE | 🔒 SS | @ip_cf_config [1], 🇮🇷 IR | 🔒 SS | @jeyksatan [7], 🇺🇸 US | 🔒 SS | @jeyksatan [8], 🇺🇸 US | 🔒 SS | @megavpn_link [5], ❔ XX | 🔒 SS | @mt_proxy [5], 🇺🇸 US | 🔒 SS | @nationalproxytelegram [2], 🇺🇸 US | 🔒 SS | @nepo_v2ray [14], 🇺🇸 US | 🔒 SS | @nepo_v2ray [19], 🇬🇮 GI | 🔒 SS | @outline_ir [8], ❔ XX | 🔒 SS | @proxy_confiingir [2], ❔ XX | 🔒 SS | @public504 [8], ❔ XX | 🔒 SS | @public504 [9], ❔ XX | 🔒 SS | @red2ray [1], 🇺🇸 US | 🔒 SS | @torang_vpn [4], 🇺🇸 US | 🔒 SS | @v2rayngalpha [2], 🇳🇱 NL | 🔒 SS | @v2rayngrit [7], 🇺🇸 US | 🔒 SS | @vpn451 [3], 🇳🇱 NL | 🔒 SS | @vpn451 [6], 🇳🇱 NL | 🔒 SS | @vpn451 [8], 🇯🇵 JP | 🔒 SS | @vpn451 [9], 🇺🇸 US | 🔒 SS | @vpn451 [10]
PSG-FALLBACK = fallback, ❔ XX | 🔒 SS | @ai_duet [7], 🇺🇸 US | 🔒 SS | @freeconfigsplus [11], 🇺🇸 US | 🔒 SS | @freeconfigsplus [13], 🇺🇸 US | 🔒 SS | @freevirgoolnet [1], 🇸🇪 SE | 🔒 SS | @ip_cf_config [1], 🇮🇷 IR | 🔒 SS | @jeyksatan [7], 🇺🇸 US | 🔒 SS | @jeyksatan [8], 🇺🇸 US | 🔒 SS | @megavpn_link [5], ❔ XX | 🔒 SS | @mt_proxy [5], 🇺🇸 US | 🔒 SS | @nationalproxytelegram [2], 🇺🇸 US | 🔒 SS | @nepo_v2ray [14], 🇺🇸 US | 🔒 SS | @nepo_v2ray [19], 🇬🇮 GI | 🔒 SS | @outline_ir [8], ❔ XX | 🔒 SS | @proxy_confiingir [2], ❔ XX | 🔒 SS | @public504 [8], ❔ XX | 🔒 SS | @public504 [9], ❔ XX | 🔒 SS | @red2ray [1], 🇺🇸 US | 🔒 SS | @torang_vpn [4], 🇺🇸 US | 🔒 SS | @v2rayngalpha [2], 🇳🇱 NL | 🔒 SS | @v2rayngrit [7], 🇺🇸 US | 🔒 SS | @vpn451 [3], 🇳🇱 NL | 🔒 SS | @vpn451 [6], 🇳🇱 NL | 🔒 SS | @vpn451 [8], 🇯🇵 JP | 🔒 SS | @vpn451 [9], 🇺🇸 US | 🔒 SS | @vpn451 [10]

[Rule]
GEOIP,IR,DIRECT
FINAL,PSG-MANUAL
